// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacXAkm8iJp-5FWGToMi5oRv_4ji6EJUA',
    appId: '1:23616863933:android:c381b3a4d253675cb4c1d4',
    messagingSenderId: '23616863933',
    projectId: 'fir-test-cb00e',
    databaseURL: 'https://fir-test-cb00e-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-cb00e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe083tms6JaLJ4qmdvz4KBPRMVC8zT6-A',
    appId: '1:23616863933:ios:0da9c9c142989652b4c1d4',
    messagingSenderId: '23616863933',
    projectId: 'fir-test-cb00e',
    databaseURL: 'https://fir-test-cb00e-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-cb00e.appspot.com',
    iosClientId: '23616863933-riu5gmt321o73rqbjikfep8bij77uok2.apps.googleusercontent.com',
    iosBundleId: 'jmapps.test.fireBase',
  );
}
